{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "23RjFIceRZ6I",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "9673bde5-8fbc-4fdc-d78c-fd91c24eb5c0"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Sheets: ['Outbound', 'BranchMaster', 'CostCurve', 'CurrentScenario']\n",
            "\n",
            "========================================\n",
            "Sheet: Outbound\n",
            "========================================\n",
            "<class 'pandas.core.frame.DataFrame'>\n",
            "RangeIndex: 145490 entries, 0 to 145489\n",
            "Data columns (total 9 columns):\n",
            " #   Column                     Non-Null Count   Dtype  \n",
            "---  ------                     --------------   -----  \n",
            " 0   DestinationRef             145490 non-null  object \n",
            " 1   DestinationType            145490 non-null  object \n",
            " 2   ShipToID                   145490 non-null  object \n",
            " 3   GroupID                    145490 non-null  int64  \n",
            " 4   Longitude                  145490 non-null  float64\n",
            " 5   Latitude                   145490 non-null  float64\n",
            " 6   BranchDeliveryVolumeInKG   145490 non-null  float64\n",
            " 7   BranchDeliveryVolumeInCBM  145490 non-null  float64\n",
            " 8   Section                    145490 non-null  object \n",
            "dtypes: float64(4), int64(1), object(4)\n",
            "memory usage: 10.0+ MB\n",
            "None\n",
            "\n",
            "Missing values:\n",
            "DestinationRef               0\n",
            "DestinationType              0\n",
            "ShipToID                     0\n",
            "GroupID                      0\n",
            "Longitude                    0\n",
            "Latitude                     0\n",
            "BranchDeliveryVolumeInKG     0\n",
            "BranchDeliveryVolumeInCBM    0\n",
            "Section                      0\n",
            "dtype: int64\n",
            "Total Missing: 0\n",
            "\n",
            "Duplicate rows: 3\n",
            "\n",
            "DestinationRef\n",
            "Missing: 0\n",
            "Duplicate: 144855\n",
            "\n",
            "ShipToID\n",
            "Missing: 0\n",
            "Duplicate: 145004\n",
            "\n",
            "GroupID\n",
            "Missing: 0\n",
            "Duplicate: 144551\n",
            "\n",
            "Invalid Latitude: 0\n",
            "Invalid Longitude: 0\n",
            "Negative KG: 0\n",
            "Negative CBM: 0\n",
            "\n",
            "========================================\n",
            "Sheet: BranchMaster\n",
            "========================================\n",
            "<class 'pandas.core.frame.DataFrame'>\n",
            "RangeIndex: 635 entries, 0 to 634\n",
            "Data columns (total 10 columns):\n",
            " #   Column           Non-Null Count  Dtype  \n",
            "---  ------           --------------  -----  \n",
            " 0   DestinationRef   635 non-null    object \n",
            " 1   DestinationType  635 non-null    object \n",
            " 2   ShipToID         635 non-null    object \n",
            " 3   Longitude        635 non-null    float64\n",
            " 4   Latitude         635 non-null    float64\n",
            " 5   Suburb           635 non-null    object \n",
            " 6   City             635 non-null    object \n",
            " 7   SA4              633 non-null    object \n",
            " 8   State            635 non-null    object \n",
            " 9   Country          635 non-null    object \n",
            "dtypes: float64(2), object(8)\n",
            "memory usage: 49.7+ KB\n",
            "None\n",
            "\n",
            "Missing values:\n",
            "DestinationRef     0\n",
            "DestinationType    0\n",
            "ShipToID           0\n",
            "Longitude          0\n",
            "Latitude           0\n",
            "Suburb             0\n",
            "City               0\n",
            "SA4                2\n",
            "State              0\n",
            "Country            0\n",
            "dtype: int64\n",
            "Total Missing: 2\n",
            "\n",
            "Duplicate rows: 0\n",
            "\n",
            "DestinationRef\n",
            "Missing: 0\n",
            "Duplicate: 0\n",
            "\n",
            "ShipToID\n",
            "Missing: 0\n",
            "Duplicate: 149\n",
            "\n",
            "Invalid Latitude: 0\n",
            "Invalid Longitude: 0\n"
          ]
        }
      ],
      "source": [
        "import os\n",
        "import math\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "\n",
        "# Đọc file Excel\n",
        "sheets = pd.read_excel(\"Research_Project_Data.xlsx\", sheet_name=None)\n",
        "\n",
        "# Xem tên các sheet\n",
        "print(\"Sheets:\", list(sheets.keys()))\n",
        "\n",
        "# Lấy 2 sheet cần kiểm tra\n",
        "outbound = sheets[\"Outbound\"]\n",
        "branchmaster = sheets[\"BranchMaster\"]\n",
        "\n",
        "# Hàm kiểm tra dữ liệu\n",
        "def check_data(df, sheet_name):\n",
        "\n",
        "    print(\"\\n\" + \"=\"*40)\n",
        "    print(f\"Sheet: {sheet_name}\")\n",
        "    print(\"=\"*40)\n",
        "\n",
        "    # Xem thông tin dữ liệu\n",
        "    print(df.info())\n",
        "\n",
        "    # 1. Missing values\n",
        "    print(\"\\nMissing values:\")\n",
        "    print(df.isnull().sum())\n",
        "    print(\"Total Missing:\", df.isnull().sum().sum())\n",
        "\n",
        "    # 2. Duplicate rows\n",
        "    print(\"\\nDuplicate rows:\", df.duplicated().sum())\n",
        "\n",
        "    # 3. Duplicate ID\n",
        "    for col in [\"DestinationRef\", \"ShipToID\", \"GroupID\"]:\n",
        "        if col in df.columns:\n",
        "            print(f\"\\n{col}\")\n",
        "            print(\"Missing:\", df[col].isnull().sum())\n",
        "            print(\"Duplicate:\", df[col].duplicated().sum())\n",
        "\n",
        "    # 4. Invalid values\n",
        "    if \"Latitude\" in df.columns:\n",
        "        print(\"\\nInvalid Latitude:\",\n",
        "              ((df[\"Latitude\"] < -90) | (df[\"Latitude\"] > 90)).sum())\n",
        "\n",
        "    if \"Longitude\" in df.columns:\n",
        "        print(\"Invalid Longitude:\",\n",
        "              ((df[\"Longitude\"] < -180) | (df[\"Longitude\"] > 180)).sum())\n",
        "\n",
        "    # 5. Unit check (KG & CBM)\n",
        "    if \"BranchDeliveryVolumeInKG\" in df.columns:\n",
        "        print(\"Negative KG:\",\n",
        "              (df[\"BranchDeliveryVolumeInKG\"] < 0).sum())\n",
        "\n",
        "    if \"BranchDeliveryVolumeInCBM\" in df.columns:\n",
        "        print(\"Negative CBM:\",\n",
        "              (df[\"BranchDeliveryVolumeInCBM\"] < 0).sum())\n",
        "\n",
        "# Chạy kiểm tra cho 2 sheet\n",
        "check_data(outbound, \"Outbound\")\n",
        "check_data(branchmaster, \"BranchMaster\")"
      ]
    }
  ]
}
